name: Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '20'
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        node-version: '20'
        
    - uses: Silleellie/pylint-github-action@v2
      with:
        lint-path: >
          testing/tester.py
          src/*.py
        python-version: 3.9
        color-good-score: brightgreen
        color-perfect-score: brightgreen
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint testing/tester.py src/fridge_bot.py src/bluefors_comm.py
